branch-defaults:
  master:
    environment: mockserver
deploy:
  artifact: ../../dist/MockServer.zip
environment-defaults:
  mockserver:
    branch: null
    repository: null
global:
  application_name: mock-server
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:eu-west-2::platform/Java 8 running on
    64bit Amazon Linux/2.6.0
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
